name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Gradle Build
        uses: actions/cache@v3
        with:
          path: .gradle/build-cache
          key: ${{ runner.os }}-gradle-build-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-build-cache-${{ github.ref }}-
            ${{ runner.os }}-gradle-build-cache-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: |
          #       a etapa "Build and Test" ainda existiria, mas não faria nada.
          #       A job "build" ainda seria encontrada e executaria as etapas anteriores.
          if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.ref_name }}" == "develop" ]]; then
          echo "Running debug build and tests for PR or develop branch..."
          ./gradlew assembleDebug testDebugUnitTest --stacktrace --scan
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref_name }}" == "main" ]]; then
          echo "Running release build for main branch..."
          ./gradlew assembleRelease --stacktrace --scan
          else
          echo "Running default (debug) build and tests as fallback..."
          ./gradlew assembleDebug testDebugUnitTest --stacktrace --scan
          fi
